Fail pipeline if HIGH/CRITICAL vulnerabilities found
Add a step to fail the pipeline on HIGH/CRITICAL vulnerabilities.

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -202,3 +202,9 @@ jobs:
           image-ref: 'orden-service-img'
           severity: 'HIGH,CRITICAL'
           ignore-unfixed: true
+      - name: Falla si HIGH/CRITICAL se hallan vulnerabilidades
+        run: |
+          if grep -R "CRITICAL\|HIGH" trivy*; then
+            echo "Vulnerabilities detected. Failing pipeline."
+            exit 1
+          fi || true
